### ISSUE TITLE
Sidebar UI glitch

### ISSUE THREAD

**Issue by krushna06** [Bot-Rakshit/bm_frontend#46] opened 2024-07-18 09:43 UTC
The logout button on the sidebar seem to break due to auto-slide-in slide-out. UI bug

**Comment by Prathamesh-B** [comment] 2024-07-18 13:10
It breaks when we click on the profile button and move the cursor out

https://github.com/user-attachments/assets/a4c4dc18-3c0c-4f56-9a7b-367a935d933b

**Comment by Sparsh-Malhotra** [comment] 2024-07-18 15:50
Yeah I can see this glitch. Picking it up @Bot-Rakshit

**Comment by ARSHIL1804** [comment] 2024-07-19 04:45
Hey @Sparsh-Malhotra , While your solution resolves this issue but when we move the mouse away from the Logout button, some kind of glitch happens on the sidebar as shown in the video below. I think we should not trigger the side bar close when the Dropdown is open. I will be raising one PR for that 

CC:  @Bot-Rakshit @krushna06 @Prathamesh-B

**Comment by Sparsh-Malhotra** [comment] 2024-07-19 04:49
@ARSHIL1804 Actually its the other way around. I am closing the dropdown when the sidebar is collapsing which makes sense. You dont want to keep the dropdown state even if the sidebar has already collapsed. Could you please share what glitch is still there in my solution and what kind of approach are you working on before raising the PR ?

**Comment by ARSHIL1804** [comment] 2024-07-19 04:54
So I was thinking about using an event variable and checking if event.relatedTarget (which gives the new element where mouse pointer is) is equal to event.currentTarget (which will be a sidebar div in our case). If this both is same then we don't want to close sidebar else we will close this.

**Comment by Sparsh-Malhotra** [comment] 2024-07-19 05:12
https://www.loom.com/share/b50daecdc3ac4d39987601657313d534

@ARSHIL1804 I am unable to reproduce the bug in my branch. Could you please checkout the branch and share the steps to reproduce it ?

**Comment by ARSHIL1804** [comment] 2024-07-19 05:15
You are not doing it properly. Hover on Logout and leave Logout button and go to sidebar not outside of sidebar

**Comment by Sparsh-Malhotra** [comment] 2024-07-19 05:25
Got it @ARSHIL1804. Just check if we can improve the existing sidebar and dropdown logic. Right now we have dependency on too many states. Fixing this logic might fix #48 as well

**Closed** 2024-07-19 15:15 UTC
